"""
File generation service.

Converts validated form payloads into the exact YAML and CSV formats that
the dumpling Snakemake pipeline expects.
"""
from __future__ import annotations
import csv
import io
import zipfile
import yaml
from app.models.config import ConfigPayload
from app.models.experiments import ExperimentsPayload

# Keys that should be omitted from the output when they are empty strings
# (as opposed to meaningful empty string defaults like baseline_condition).
_OPTIONAL_PATH_KEYS = {"oligo_file", "variants_file"}

# Long comment header preserved in generated YAML so the file is self-documenting.
_CONFIG_HEADER = """\
# Configuration for DMS analysis
# Generated by dumpling-helpers — edit as needed before running Snakemake.
# Validated against: workflow/schemas/config.schema.yaml
"""


def build_config_dict(payload: ConfigPayload) -> dict:
    """
    Convert a ConfigPayload into the dict that will be serialised as YAML.
    Omits optional path fields when blank, and collapses single-item lists.
    """
    data = payload.model_dump()

    for key in _OPTIONAL_PATH_KEYS:
        if not data.get(key):
            data.pop(key, None)

    # adapters / contaminants: normalise; accept comma-separated strings or lists
    for key in ("adapters", "contaminants"):
        val = data.get(key, [])
        if isinstance(val, str):
            val = [v.strip() for v in val.split(",") if v.strip()]
        if len(val) == 0:
            data.pop(key, None)
        elif len(val) == 1:
            data[key] = val[0]
        else:
            data[key] = val

    # omit empty strings that carry no meaning when blank
    for key in ("baseline_condition",):
        if data.get(key) == "":
            data.pop(key, None)

    # remove_zeros is only meaningful when enrich2 is enabled
    if not data.get("enrich2"):
        data.pop("remove_zeros", None)

    # oligo_file only relevant when regenerate_variants is true
    if not data.get("regenerate_variants"):
        data.pop("oligo_file", None)

    return data


def generate_yaml(payload: ConfigPayload) -> str:
    data = build_config_dict(payload)
    return _CONFIG_HEADER + yaml.dump(
        data,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
    )


def generate_csv(payload: ExperimentsPayload) -> str:
    buf = io.StringIO()

    fieldnames = ["sample", "condition", "replicate"]
    if payload.mode == "timecourse":
        fieldnames.append("time")
    else:
        fieldnames.append("bin")
    if payload.include_tile:
        fieldnames.append("tile")
    fieldnames.append("file")

    writer = csv.DictWriter(buf, fieldnames=fieldnames, lineterminator="\n")
    writer.writeheader()

    for row in payload.rows:
        row_dict = row.model_dump(exclude_none=True)
        # Map the canonical "time" or "bin" from the row model
        out: dict = {
            "sample": row_dict["sample"],
            "condition": row_dict["condition"],
            "replicate": row_dict["replicate"],
            "file": row_dict["file"],
        }
        if payload.mode == "timecourse":
            out["time"] = row_dict.get("time", 0)
        else:
            out["bin"] = row_dict.get("bin", 1)
        if payload.include_tile:
            out["tile"] = row_dict.get("tile", 1)
        writer.writerow(out)

    return buf.getvalue()


def generate_zip(config_payload: ConfigPayload, experiments_payload: ExperimentsPayload) -> bytes:
    """Return a ZIP archive containing config.yaml and experiments.csv."""
    config_yaml = generate_yaml(config_payload)
    experiments_csv = generate_csv(experiments_payload)

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("config.yaml", config_yaml)
        zf.writestr("experiments.csv", experiments_csv)
    return buf.getvalue()
