import yaml from 'js-yaml'
import Papa from 'papaparse'
import type { ConfigFormValues } from '@/schemas/config'
import type { SampleRowValues } from '@/schemas/samples'

function splitList(s: string): string[] {
  return s.split(',').map((x) => x.trim()).filter(Boolean)
}

/**
 * Build the nested plain object that becomes config.yaml. Top-level sections are
 * always emitted (they carry schema defaults); optional fusion_library entries
 * are included only when non-empty.
 */
export function buildConfigObject(c: ConfigFormValues): Record<string, unknown> {
  const fl: Record<string, unknown> = {
    retained: {
      name: c.fusion_library.retained.name,
      position: c.fusion_library.retained.position,
      truncated_component: c.fusion_library.retained.truncated_component,
    },
    linker_sequence: c.fusion_library.linker_sequence,
    partners_file: c.fusion_library.partners_file,
    sequences_file: c.fusion_library.sequences_file,
  }

  if (c.fusion_library.variant_retained.length > 0) {
    fl.variant_retained = c.fusion_library.variant_retained.map((v) => {
      const entry: Record<string, unknown> = { name: v.name }
      const partners = splitList(v.partners)
      if (v.all_partners) entry.all_partners = true
      else if (partners.length > 0) entry.partners = partners
      if (v.description) entry.description = v.description
      return entry
    })
  }
  if (c.fusion_library.unfused_sequences_file)
    fl.unfused_sequences_file = c.fusion_library.unfused_sequences_file
  if (c.fusion_library.exon_partners_file)
    fl.exon_partners_file = c.fusion_library.exon_partners_file

  return {
    experiment: c.experiment,
    data_dir: c.data_dir,
    ref_dir: c.ref_dir,
    samples_file: c.samples_file,
    fusion_library: fl,
    detection: { ...c.detection },
    sequencing: { ...c.sequencing },
    preprocessing: {
      adapters: c.preprocessing.adapters,
      contaminants: splitList(c.preprocessing.contaminants),
    },
    qc: { ...c.qc },
    pipeline: { ...c.pipeline },
    resources: { ...c.resources },
    quick: {
      enabled: c.quick.enabled,
      max_reads: c.quick.max_reads,
      fraction: c.quick.fraction, // explicit null when unset
      seed: c.quick.seed,
    },
  }
}

export function buildConfigYaml(c: ConfigFormValues): string {
  try {
    return (
      '# Generated by dumpling-helpers (fusilli)\n' +
      yaml.dump(buildConfigObject(c), { lineWidth: 100, sortKeys: false })
    )
  } catch {
    return '# (invalid config — check your inputs)'
  }
}

const SAMPLE_COLUMNS = ['sample', 'condition', 'replicate', 'time', 'tile', 'file']

export function buildSamplesCsv(rows: SampleRowValues[]): string {
  if (rows.length === 0) return ''
  const data = rows.map((r) => ({
    sample: r.sample,
    condition: r.condition,
    replicate: r.replicate,
    time: r.time,
    tile: r.tile,
    file: r.file,
  }))
  return Papa.unparse(data, { columns: SAMPLE_COLUMNS, newline: '\n' })
}
