import yaml from 'js-yaml'
import Papa from 'papaparse'
import type { ConfigFormValues } from '@/schemas/config'
import type { SampleRowValues } from '@/schemas/samples'

export function buildConfigObject(c: ConfigFormValues): Record<string, unknown> {
  const o: Record<string, unknown> = {
    experiment: c.experiment,
    data_dir: c.data_dir,
    ref_dir: c.ref_dir,
    experiment_file: c.experiment_file,
    reference: c.reference,
    orf: c.orf,
    flanking_sequence: c.flanking_sequence,
    barcode_distance: c.barcode_distance,
    max_barcode_length: c.max_barcode_length,
    min_cluster_size: c.min_cluster_size,
    mpileup_max_depth: c.mpileup_max_depth,
    use_qual: c.use_qual,
    call_fract: c.call_fract,
    calling_mode: c.calling_mode,
    qc_min_af: c.qc_min_af,
    qc_min_alt_reads: c.qc_min_alt_reads,
    clash_merge_fraction: c.clash_merge_fraction,
    clash_mixed_af: c.clash_mixed_af,
    exclude_clashes: c.exclude_clashes,
  }
  // gene_name defaults to the reference name when unset, so omit it if blank.
  if (c.gene_name) o.gene_name = c.gene_name
  return o
}

export function buildConfigYaml(c: ConfigFormValues): string {
  try {
    return (
      '# Generated by dumpling-helpers (stromboli)\n' +
      yaml.dump(buildConfigObject(c), { lineWidth: 100, sortKeys: false })
    )
  } catch {
    return '# (invalid config — check your inputs)'
  }
}

const SAMPLE_COLUMNS = ['sample', 'file']

export function buildSamplesCsv(rows: SampleRowValues[]): string {
  if (rows.length === 0) return ''
  const data = rows.map((r) => ({ sample: r.sample, file: r.file }))
  return Papa.unparse(data, { columns: SAMPLE_COLUMNS, newline: '\n' })
}
